version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - npm run build
artifacts:
  files:
    - .next/*
    - node_modules
    - aws/config.json
    - public
    - next*
